### ISSUE TITLE
CheckTx in example mutates the state?

### ISSUE THREAD

**Issue by NodeGuy** [tendermint/js-abci#1]
Why does the example increment `this.txCount` in `checkTx`?  Isn't that mutating the state, which is contrary to the purpose of `checkTx`?

https://github.com/tendermint/js-tmsp/blob/master/example/app.js#L59

**Comment by ebuchman** [comment]
I believe you're correct. Really, though, it should maintain an intermediate state for tracking validity of chains of transactions before they end up in a block.
