### ISSUE TITLE
Update for v0.10.0

### ISSUE THREAD

**Issue by ebuchman** [tendermint/js-abci#14]
Breaking changes.

See [Changelog](https://github.com/tendermint/abci/blob/master/CHANGELOG.md#0100-february-20-2018) for overview. Main items are:
 - New [socket length prefixing](https://github.com/tendermint/abci#socket-tsp)
 - Updated [specification](https://github.com/tendermint/abci/blob/master/specification.rst) for [proto file change](https://github.com/tendermint/abci/blob/master/types/types.proto)

**Comment by mappum** [comment]
Now updated for 0.19.
