### ISSUE TITLE
Update js-abci to make it compatible with tendermint 0.19

### ISSUE THREAD

**Issue by panda-sandeep** [tendermint/js-abci#15]
Hi everyone!

We have been using tendermint along with `js-abci` for some internal PoCs and we think it's really great. However, `js-abci` doesn't work with the latest tendermint (0.19). So, we ended up using tendermint 0.13 + js-abci. 

Can this be updated to work with the latest tendermint? I am also aware of [lotion.js](https://github.com/keppel/lotion) which works with the latest tendermint, but I really like the low-level controls/functionalities that `js-abci` offers.

Thanks for building tendermint and js-abci. 👍

**Comment by mappum** [comment]
Hey @sandeeppanda92, thanks for opening an issue.

I recently rewrote this module and updated it for Tendermint 0.19, feel free to upgrade. Note that the package name on npm is now `abci` (no `js-` prefix).
