### ISSUE TITLE
Should this basic example work on version Tendermint Version 0.15?

### ISSUE THREAD

**Issue by arsen3d** [tendermint/js-abci#18]
<img width="1284" alt="screen shot 2018-05-11 at 9 50 05 pm" src="https://user-images.githubusercontent.com/298235/39953652-68428814-5565-11e8-8a58-01140ca23c15.png">

**Comment by zramsay** [comment]
which example are you using? what's the app you're running in the background? if the only thing you're running is `tendermint node` that won't work unless you [run an abci app to connect to seperately](http://tendermint.readthedocs.io/en/master/getting-started.html). Note that you can get around installing abci with `tendermint node --proxy_app=kvstore`

**Comment by mappum** [comment]
@arsen3d, I would guess maybe the error in your console is preventing the ABCI server from starting. Try logging something to ensure the server starts listening (`server.listen(46658, () => console.log('ABCI server listening on port 46658'))`).

**Comment by zramsay** [comment]
works to at least 0.19 (see https://github.com/tendermint/js-abci#js-abci)
