### ISSUE TITLE
Inconsistencies between docs and js-abci

### ISSUE THREAD

**Issue by Ivshti** [tendermint/js-abci#21]
I discovered a few inconsistencies between the docs ( https://tendermint.readthedocs.io/en/master/getting-started.html ) and the latest version of this repo

1. The tutorial references `example/app.js`, when this repo has `example/counter.js`
2. Tendermint, as started in the way specified in the example (`tendermint init`, `tendermint node`) seems to expect the example to run on port `26658` rather than `46658` (also referenced here: https://github.com/tendermint/js-abci/issues/18)
3. Not really an inconsistency, but couldn't figure out why it's so: `require('abci')` is not going to work in `examples/counterjs`, unless `abci` is linked as a module; perhaps it should be `require('..')` so it can run for people who are trying to follow the tutorial?

**EDIT:** For some reason I thought `abci` was not on `npmjs`, that was my mistake; I still think that the tutorial should "work" when you follow it step by step, so this should be addressed in some way; perhaps add `npm link` in the tutorial or something

**Comment by zramsay** [comment]
Thanks for reporting these issues. Points 1 and 2 fixed with the above commits/PRs. @mappum can address point 3

**Comment by Ivshti** [comment]
thanks for the quick fixes!

regarding point 3, I just edited my issue report cause I realized `abci` is actually published
