### ISSUE TITLE
Facing error while posting a transaction

### ISSUE THREAD

**Issue by himanshunagda** [tendermint/js-abci#24]
i am facing this issues again and again while posting a transaction to tendermint RPC endpoint
I am using self written js-abci with abci in node modules.
request:
   method: 'POST',
    headers: headers,
    json: true,
    body: {jsonrpc: "2.0", method: "broadcast_tx_commit", params: {tx: transaction}, id: "abc"}
  
[error_log.txt](https://github.com/tendermint/js-abci/files/2395917/error_log.txt)

**Comment by himanshunagda** [comment]
@melekes Hi melekes ,any updates regarding the issue???

**Comment by radsal** [comment]
Facing the same issue. Attaching the logs from custom js-abci server.
Node version: v8.11.3
NPM version: 6.4.1
js abci module: 4.0.0
Tendermint: v0.25.0 (docker)

It did work once but most of the times it's stuck with a similar error and the tx is added to the number of unconfirmed txs.
[abci-js-log.txt](https://github.com/tendermint/js-abci/files/2428528/abci-js-log.txt)

Here is a test request.
https://gist.github.com/PradeepSalanki/3cc281ad478c95e42f334d7c18f4ceb6

**Comment by siman** [comment]
@himanshunagda, @PradeepSalanki, I believe that it was fixed recently with this commit https://github.com/tendermint/js-abci/commit/e2470014a42b59b108b95479b8dc688834060466 .
In short: there was a bug when encoding large transactions (fragmented) and @mappum fixed it recently. I had the similar problems on my side but after this update the problem's gone!

**Comment by zramsay** [comment]
closing based on @siman's comment. re-open if still an issue

**Comment by himanshunagda** [comment]
@siman Yes now it works fine thank you!
