### ISSUE TITLE
bring back updates that broke tests

### ISSUE THREAD

**Issue by zramsay** [tendermint/js-abci#32]
see #26 and #27 cc @davebryson and @marypreethi12 

Sorry I had to revert those changes, discovered broken tests (`npm test`) while implementing the CI

**Comment by davebryson** [comment]
So essentially the fixture related tests are based on byte signatures from the older protocol. So updating the fixtures to the latest signatures should resolve the issue.   Any recommendations on how to generate the signatures in the test/fixtures file?

**Comment by marypreethi12** [comment]
i fixed some typo errors which were failing CI, however now we have 3 tests failed 11 passed, is it something to do with signature which @davebryson mentioned ?

**Comment by mappum** [comment]
Just had to update a test fixture, now this targets 0.26+. (#33 was merged)
