### ISSUE TITLE
panic: Tendermint state.AppHash does not match AppHash after replay. Got , expected 0000000000000000

### ISSUE THREAD

**Issue by scalalang2** [tendermint/js-abci#37]
I have tested with counter.js examples on tendermint 0.31.5.
I think this repository does not support latest tendermint app.

**Comment by liamsi** [comment]
As a general note: a compatibility matrix ala https://github.com/jTendermint/jabci#compatibility would be helpful.

**Comment by scalalang2** [comment]
Thanks.
